steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/node:$SHORT_SHA'
  - '-f'
  - 'Dockerfile.rest'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/rest:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'set'
  - 'image'
  - 'deployment/rest'
  - 'rest=gcr.io/$PROJECT_ID/rest:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
timeout: '1600s'