#cloudbuild.yaml
steps:
- id: 'build 3 node testnet'
  name: 'docker/compose:1.19.0'
  args: ['up', '--build', '-d']
  # args: ['up', '-d']
- id: 'multi-node integration test'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-f', 'Dockerfile_3ntest', '--network', 'cloudbuild']
  waitFor: ['build 3 node testnet']
- name: 'docker/compose:1.19.0'
  args: ['down']
  waitFor: ['multi-node integration test']
# reference https://github.com/GoogleCloudPlatform/cloudbuild-integration-testing/blob/master/docker-compose.yml