version: '3.8'
services:
  node0:
    build:
      context: .
      target: pylonsd
    secrets:
      - source: val_key
        target: /root/.pylonsd/config/priv_validator_key.json
      - source: genesis
        target: /root/.pylonsd/config/genesis.json
      - source: config
        target: /root/.pylonsd/config/config.toml
    networks:
      testnet:
        ipv4_address: 192.168.10.0

  node1:
    build:
      context: .
      target: pylonsd
    secrets:
      - source: val_key
        target: /root/.pylonsd/config/priv_validator_key.json
      - source: genesis
        target: /root/.pylonsd/config/genesis.json
      - source: config
        target: /root/.pylonsd/config/config.toml
    networks:
      testnet:
        ipv4_address: 192.168.10.1
  node2:
    build:
      context: .
      target: pylonsd
    secrets:
      - source: val_key
        target: /root/.pylonsd/config/priv_validator_key.json
      - source: genesis
        target: /root/.pylonsd/config/genesis.json
      - source: config
        target: /root/.pylonsd/config/config.toml
    ports:
      - "26656-26657:26656-26657"
    networks:
      testnet:
        ipv4_address: 192.168.10.2

secrets:
  val_key:
    file: ./production_config/pylonsd/val_0_key.json
  genesis:
    file: ./production_config/pylonsd/genesis.json
  config:
    file: ./production_config/pylonsd/config.toml
networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
