version: '3'
services:
  node0:
    build:
      context: .
      target: pylonsd
    secrets:
      - source: val_key
        target: /root/.pylonds/config/priv_validator_key.json
    ports:
      - "26656-26657:26656-26657"
    networks:
      testnet:
        ipv4_address: 192.168.10.2
secrets:
  val_key:
    file: ./production_config/pylonsd/val_0_key.json
networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
