apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.prod-like.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node2
  name: node2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.prod-like.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/testnet: "true"
        io.kompose.service: node2
    spec:
      containers:
      - image: node2
        imagePullPolicy: ""
        name: node2
        ports:
        - containerPort: 26656
        - containerPort: 26657
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
