# See: https://dart.dev/guides/language/analysis-options
---
include: package:pedantic/analysis_options.1.9.0.yaml
analyzer:
  exclude:
    - example/**.dart
linter:
  rules:
    prefer_single_quotes: false
