genesis:
  chain_id: "pylons"

build:
  binary: "pylonsd"

init:
  home: "$HOME/.pylonsd"
  config:
    api:
      swagger: false

accounts:
  - name: pylonsinc
    coins: ["9000000000pylon,900000000bedrock"]
    mnemonic: "achieve patch rabbit delay you stairs flag nation lady outside answer property olive man dwarf used chapter sunset bundle sniff between since review logic"
  - name: tendermint
    coins: ["1000000000pylon,100000000bedrock"]
    mnemonic: "oil inflict cup nation circle palace cactus uphold clarify vibrant believe stem farm aerobic casino treat early amazing remain produce exhaust bachelor flame own"


validator:
  name: pylonsinc
  staked: "300000000bedrock"