export const PDF = 'pdf'
export const AUDIO = 'audio'
export const VIDEO = 'video'
export const IMAGE = 'image'
export const THREED = '3d'
export const THUMBNAILURL = 'Thumbnail_URL'
export const NFTURL = 'NFT_URL'
