version: '3.4'
services:

  alpha:
    hostname: alpha
    container_name: alpha
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26656-26657:26656-26657"
    networks:
      - pylonsnet
    volumes:
      - ./alpha:/root/.pylonsd

  beta:
    container_name: beta
    hostname: beta
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26659-26660:26656-26657"
    networks:
      - pylonsnet
    volumes:
      - ./beta:/root/.pylonsd

  gamma:
    container_name: gamma
    hostname: gamma
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26661-26662:26656-26657"
    networks:
      - pylonsnet
    volumes:
      - ./gamma/:/root/.pylonsd

#
#
#  fullnode:
#    hostname: fullnode
#    depends_on:
#      - coordinator
#    build:
#      dockerfile: Dockerfile.starport
#      context: .
#      target: fullnode
#    ports:
#      - "1317:1317"
#    networks:
#      - pylonsnet
#
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    hostname: mongo
#    networks:
#      - pylonsnet
#    command:
#      - --storageEngine=wiredTiger
#    volumes:
#      - data:/data/db
#
#  big-dipper:
#    image: rafaeldeandrade/big-dipper:v0.0.3
#    container_name: explorer
#    hostname: explorer
#    ports:
#      - "3000:3000"
#    networks:
#      - pylonsnet
#    depends_on:
#      - mongo
#    environment:
#      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
#      MONGO_URL: mongodb://mongo:27017/meteor
#      METEOR_SETTINGS: ${METEOR_SETTINGS}
#      PORT: 3000

networks:
  pylonsnet:

volumes:
  pylons_home:
  data:
  alpha_data:
  beta_data:
  gamma_data:
