version: '3.4'
services:

  alpha:
    hostname: alpha
    container_name: alpha
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    networks:
      localnet:
        ipv4_address: 192.168.10.2
    volumes:
      - ./alpha:/root/.pylons:Z

  beta:
    container_name: beta
    hostname: beta
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26659:26656"
      - "26660:26656"
      - "1318:1317"
    networks:
      localnet:
        ipv4_address: 192.168.10.3
    volumes:
      - ./beta:/root/.pylons:Z

  gamma:
    container_name: gamma
    hostname: gamma
    build:
      context: .
      args:
        - CONFIG_DIR=alpha
    ports:
      - "26661:26656"
      - "26662:26657"
      - "1319:1317"
    networks:
      localnet:
        ipv4_address: 192.168.10.4
    volumes:
      - ./gamma/:/root/.pylons:Z

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    networks:
      localnet:
        ipv4_address: 192.168.10.5
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db:Z

  big-dipper:
    image: rafaeldeandrade/big-dipper:v0.0.3
    container_name: explorer
    hostname: explorer
    ports:
      - "3000:3000"
    networks:
      localnet:
        ipv4_address: 192.168.10.6
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      METEOR_SETTINGS: ${METEOR_SETTINGS}
      PORT: 3000

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16

volumes:
  data:
  alpha_data:
  beta_data:
  gamma_data:
