// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gate/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryMaxTxsPerBlockRequest struct {
}

func (m *QueryMaxTxsPerBlockRequest) Reset()         { *m = QueryMaxTxsPerBlockRequest{} }
func (m *QueryMaxTxsPerBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMaxTxsPerBlockRequest) ProtoMessage()    {}
func (*QueryMaxTxsPerBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c31bd8e4314f6f, []int{0}
}
func (m *QueryMaxTxsPerBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMaxTxsPerBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMaxTxsPerBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMaxTxsPerBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMaxTxsPerBlockRequest.Merge(m, src)
}
func (m *QueryMaxTxsPerBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMaxTxsPerBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMaxTxsPerBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMaxTxsPerBlockRequest proto.InternalMessageInfo

type QueryMaxTxsPerBlockResponse struct {
	MaxTxs int64 `protobuf:"varint,1,opt,name=max_txs,json=maxTxs,proto3" json:"max_txs,omitempty"`
}

func (m *QueryMaxTxsPerBlockResponse) Reset()         { *m = QueryMaxTxsPerBlockResponse{} }
func (m *QueryMaxTxsPerBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMaxTxsPerBlockResponse) ProtoMessage()    {}
func (*QueryMaxTxsPerBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c31bd8e4314f6f, []int{1}
}
func (m *QueryMaxTxsPerBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMaxTxsPerBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMaxTxsPerBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMaxTxsPerBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMaxTxsPerBlockResponse.Merge(m, src)
}
func (m *QueryMaxTxsPerBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMaxTxsPerBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMaxTxsPerBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMaxTxsPerBlockResponse proto.InternalMessageInfo

func (m *QueryMaxTxsPerBlockResponse) GetMaxTxs() int64 {
	if m != nil {
		return m.MaxTxs
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryMaxTxsPerBlockRequest)(nil), "Pylonstech.pylons.gate.QueryMaxTxsPerBlockRequest")
	proto.RegisterType((*QueryMaxTxsPerBlockResponse)(nil), "Pylonstech.pylons.gate.QueryMaxTxsPerBlockResponse")
}

func init() { proto.RegisterFile("gate/query.proto", fileDescriptor_93c31bd8e4314f6f) }

var fileDescriptor_93c31bd8e4314f6f = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x4b, 0x33, 0x31,
	0x18, 0xc7, 0x9b, 0xf7, 0xc5, 0x0a, 0x19, 0x44, 0x0e, 0x51, 0xb9, 0xd6, 0x20, 0x75, 0x91, 0x82,
	0x09, 0x6d, 0xc1, 0x0f, 0x50, 0x5c, 0x85, 0x5a, 0x9c, 0x5c, 0x24, 0x77, 0x84, 0xf4, 0xf0, 0xee,
	0x9e, 0xf4, 0x92, 0x93, 0xdc, 0xea, 0x27, 0x10, 0xdc, 0x9d, 0xfd, 0x28, 0x8e, 0x05, 0x17, 0x47,
	0xb9, 0xf3, 0x83, 0xc8, 0x25, 0x76, 0x10, 0xea, 0xe0, 0x16, 0x78, 0x7e, 0xbf, 0xe7, 0xff, 0xe4,
	0x8f, 0x77, 0x25, 0x37, 0x82, 0x2d, 0x4b, 0x51, 0x54, 0x54, 0x15, 0x60, 0x20, 0xd8, 0x9f, 0x55,
	0x29, 0xe4, 0xda, 0x88, 0x78, 0x41, 0x95, 0x7b, 0xd2, 0x96, 0x09, 0xf7, 0x24, 0x48, 0x70, 0x08,
	0x6b, 0x5f, 0x9e, 0x0e, 0xfb, 0x12, 0x40, 0xa6, 0x82, 0x71, 0x95, 0x30, 0x9e, 0xe7, 0x60, 0xb8,
	0x49, 0x5a, 0xc5, 0x4f, 0x87, 0x31, 0xe8, 0x0c, 0x34, 0x8b, 0xb8, 0xfe, 0x0e, 0x61, 0xf7, 0xa3,
	0x48, 0x18, 0x3e, 0x62, 0x8a, 0xcb, 0x24, 0x77, 0xb0, 0x67, 0x07, 0x7d, 0x1c, 0x5e, 0xb5, 0xc4,
	0x25, 0xb7, 0xd7, 0x56, 0xcf, 0x44, 0x31, 0x4d, 0x21, 0xbe, 0x9b, 0x8b, 0x65, 0x29, 0xb4, 0x19,
	0x9c, 0xe3, 0xde, 0xc6, 0xa9, 0x56, 0x90, 0x6b, 0x11, 0x1c, 0xe0, 0xed, 0x8c, 0xdb, 0x5b, 0x63,
	0xf5, 0x21, 0x3a, 0x46, 0xa7, 0xff, 0xe7, 0xdd, 0xcc, 0x81, 0xe3, 0x17, 0x84, 0xb7, 0x9c, 0x18,
	0x3c, 0x23, 0xbc, 0xf3, 0xd3, 0x0e, 0xc6, 0x74, 0xf3, 0x5f, 0xe9, 0xef, 0x87, 0x84, 0x93, 0x3f,
	0x39, 0xfe, 0xbc, 0xc1, 0xc9, 0xc3, 0xdb, 0xe7, 0xd3, 0xbf, 0xa3, 0xa0, 0xc7, 0xbc, 0xc1, 0x5c,
	0xeb, 0xeb, 0x2a, 0x32, 0x6e, 0x8d, 0xd5, 0xd3, 0x8b, 0xd7, 0x9a, 0xa0, 0x55, 0x4d, 0xd0, 0x47,
	0x4d, 0xd0, 0x63, 0x43, 0x3a, 0xab, 0x86, 0x74, 0xde, 0x1b, 0xd2, 0xb9, 0x19, 0xca, 0xc4, 0x2c,
	0xca, 0x88, 0xc6, 0x90, 0x31, 0x9f, 0x7e, 0xd6, 0xc6, 0xaf, 0x97, 0x59, 0xbf, 0xce, 0x54, 0x4a,
	0xe8, 0xa8, 0xeb, 0xda, 0x9c, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x68, 0x03, 0x1f, 0xee, 0xd9,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	// MaxTxsInBlock provide running maxtxs, maxtxs is max txs user can sent in one block .
	MaxTxsPerBlock(ctx context.Context, in *QueryMaxTxsPerBlockRequest, opts ...grpc.CallOption) (*QueryMaxTxsPerBlockResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MaxTxsPerBlock(ctx context.Context, in *QueryMaxTxsPerBlockRequest, opts ...grpc.CallOption) (*QueryMaxTxsPerBlockResponse, error) {
	out := new(QueryMaxTxsPerBlockResponse)
	err := c.cc.Invoke(ctx, "/Pylonstech.pylons.gate.Query/MaxTxsPerBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	// MaxTxsInBlock provide running maxtxs, maxtxs is max txs user can sent in one block .
	MaxTxsPerBlock(context.Context, *QueryMaxTxsPerBlockRequest) (*QueryMaxTxsPerBlockResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MaxTxsPerBlock(ctx context.Context, req *QueryMaxTxsPerBlockRequest) (*QueryMaxTxsPerBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxTxsPerBlock not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MaxTxsPerBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMaxTxsPerBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MaxTxsPerBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pylonstech.pylons.gate.Query/MaxTxsPerBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MaxTxsPerBlock(ctx, req.(*QueryMaxTxsPerBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pylonstech.pylons.gate.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MaxTxsPerBlock",
			Handler:    _Query_MaxTxsPerBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gate/query.proto",
}

func (m *QueryMaxTxsPerBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMaxTxsPerBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMaxTxsPerBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryMaxTxsPerBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMaxTxsPerBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMaxTxsPerBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTxs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxTxs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMaxTxsPerBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryMaxTxsPerBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxTxs != 0 {
		n += 1 + sovQuery(uint64(m.MaxTxs))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMaxTxsPerBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMaxTxsPerBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMaxTxsPerBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMaxTxsPerBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMaxTxsPerBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMaxTxsPerBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTxs", wireType)
			}
			m.MaxTxs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTxs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
