package keeper_test

const (
	COMMON_SENDER     = "COMMON_SEDNER"
	COMMON_RECIPIENT  = "COMMON_RECIPIENT"
	COMMON_AMOUNT     = "1denom"
	COMMON_COOKBOOKID = "COMMON_COOKBOOKID"
	COMMON_RECIPEID   = "COMMON_RECIPEID"
	COMMON_RECEIVER   = "COMMON_RECEIVER"
)
