// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pylons/pylons/v1beta1/apple_in_app_purchase_order.proto

package v1beta1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AppleInAppPurchaseOrder struct {
	Quantity     string `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ProductId    string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseId   string `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	PurchaseDate string `protobuf:"bytes,4,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	Creator      string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *AppleInAppPurchaseOrder) Reset()         { *m = AppleInAppPurchaseOrder{} }
func (m *AppleInAppPurchaseOrder) String() string { return proto.CompactTextString(m) }
func (*AppleInAppPurchaseOrder) ProtoMessage()    {}
func (*AppleInAppPurchaseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8c656e2d72971f5, []int{0}
}
func (m *AppleInAppPurchaseOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppleInAppPurchaseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppleInAppPurchaseOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppleInAppPurchaseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppleInAppPurchaseOrder.Merge(m, src)
}
func (m *AppleInAppPurchaseOrder) XXX_Size() int {
	return m.Size()
}
func (m *AppleInAppPurchaseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_AppleInAppPurchaseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_AppleInAppPurchaseOrder proto.InternalMessageInfo

func (m *AppleInAppPurchaseOrder) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *AppleInAppPurchaseOrder) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AppleInAppPurchaseOrder) GetPurchaseId() string {
	if m != nil {
		return m.PurchaseId
	}
	return ""
}

func (m *AppleInAppPurchaseOrder) GetPurchaseDate() string {
	if m != nil {
		return m.PurchaseDate
	}
	return ""
}

func (m *AppleInAppPurchaseOrder) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*AppleInAppPurchaseOrder)(nil), "pylons.pylons.v1beta1.AppleInAppPurchaseOrder")
}

func init() {
	proto.RegisterFile("pylons/pylons/v1beta1/apple_in_app_purchase_order.proto", fileDescriptor_a8c656e2d72971f5)
}

var fileDescriptor_a8c656e2d72971f5 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0x9b, 0xef, 0xf3, 0xdf, 0x44, 0xdd, 0x04, 0xc4, 0x20, 0x18, 0x45, 0x37, 0x6e, 0x6c,
	0x19, 0x14, 0x5c, 0x8f, 0xb8, 0xe9, 0x46, 0x07, 0x97, 0x6e, 0x4a, 0xda, 0x04, 0x1b, 0x18, 0x9b,
	0x6b, 0xe6, 0x56, 0xec, 0x5b, 0xf8, 0x30, 0x3e, 0x84, 0xcb, 0x59, 0xba, 0x94, 0xf6, 0x45, 0x64,
	0x62, 0xd2, 0xd5, 0xcd, 0x3d, 0xe7, 0xfc, 0x20, 0xf7, 0xd0, 0x1b, 0xe8, 0x16, 0xb6, 0x59, 0x66,
	0x61, 0xbc, 0x4d, 0x4b, 0x8d, 0x72, 0x9a, 0x49, 0x80, 0x85, 0x2e, 0x4c, 0x53, 0x48, 0x80, 0x02,
	0x5a, 0x57, 0xd5, 0x72, 0xa9, 0x0b, 0xeb, 0x94, 0x76, 0x29, 0x38, 0x8b, 0x96, 0x1d, 0xfc, 0x11,
	0x69, 0x18, 0x01, 0x3c, 0xfb, 0x24, 0xf4, 0x70, 0xb6, 0x86, 0xf3, 0x66, 0x06, 0x30, 0x0f, 0xe4,
	0xc3, 0x1a, 0x64, 0x47, 0x74, 0xe7, 0xb5, 0x95, 0x0d, 0x1a, 0xec, 0x38, 0x39, 0x25, 0x17, 0x93,
	0xc7, 0x71, 0x67, 0xc7, 0x94, 0x82, 0xb3, 0xaa, 0xad, 0xb0, 0x30, 0x8a, 0xff, 0xf3, 0xee, 0x24,
	0x28, 0xb9, 0x62, 0x27, 0x74, 0x77, 0xfc, 0x85, 0x51, 0xfc, 0xbf, 0xf7, 0x69, 0x94, 0x72, 0xc5,
	0xce, 0xe9, 0xfe, 0x18, 0x50, 0x12, 0x35, 0xdf, 0xf0, 0x91, 0xbd, 0x28, 0xde, 0x49, 0xd4, 0x8c,
	0xd3, 0xed, 0xca, 0x69, 0x89, 0xd6, 0xf1, 0x4d, 0x6f, 0xc7, 0xf5, 0xf6, 0xfe, 0xab, 0x17, 0x64,
	0xd5, 0x0b, 0xf2, 0xd3, 0x0b, 0xf2, 0x31, 0x88, 0x64, 0x35, 0x88, 0xe4, 0x7b, 0x10, 0xc9, 0xd3,
	0xf5, 0xb3, 0xc1, 0xba, 0x2d, 0xd3, 0xca, 0xbe, 0x64, 0x73, 0x7f, 0xeb, 0x25, 0xea, 0xaa, 0x8e,
	0x85, 0xbd, 0xc7, 0x07, 0x76, 0xa0, 0xc7, 0xfe, 0xca, 0x2d, 0x5f, 0xd2, 0xd5, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0xc8, 0x08, 0x13, 0x5f, 0x01, 0x00, 0x00,
}

func (m *AppleInAppPurchaseOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppleInAppPurchaseOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppleInAppPurchaseOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAppleInAppPurchaseOrder(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PurchaseDate) > 0 {
		i -= len(m.PurchaseDate)
		copy(dAtA[i:], m.PurchaseDate)
		i = encodeVarintAppleInAppPurchaseOrder(dAtA, i, uint64(len(m.PurchaseDate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PurchaseId) > 0 {
		i -= len(m.PurchaseId)
		copy(dAtA[i:], m.PurchaseId)
		i = encodeVarintAppleInAppPurchaseOrder(dAtA, i, uint64(len(m.PurchaseId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProductId) > 0 {
		i -= len(m.ProductId)
		copy(dAtA[i:], m.ProductId)
		i = encodeVarintAppleInAppPurchaseOrder(dAtA, i, uint64(len(m.ProductId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Quantity) > 0 {
		i -= len(m.Quantity)
		copy(dAtA[i:], m.Quantity)
		i = encodeVarintAppleInAppPurchaseOrder(dAtA, i, uint64(len(m.Quantity)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAppleInAppPurchaseOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovAppleInAppPurchaseOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AppleInAppPurchaseOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Quantity)
	if l > 0 {
		n += 1 + l + sovAppleInAppPurchaseOrder(uint64(l))
	}
	l = len(m.ProductId)
	if l > 0 {
		n += 1 + l + sovAppleInAppPurchaseOrder(uint64(l))
	}
	l = len(m.PurchaseId)
	if l > 0 {
		n += 1 + l + sovAppleInAppPurchaseOrder(uint64(l))
	}
	l = len(m.PurchaseDate)
	if l > 0 {
		n += 1 + l + sovAppleInAppPurchaseOrder(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAppleInAppPurchaseOrder(uint64(l))
	}
	return n
}

func sovAppleInAppPurchaseOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAppleInAppPurchaseOrder(x uint64) (n int) {
	return sovAppleInAppPurchaseOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AppleInAppPurchaseOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAppleInAppPurchaseOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppleInAppPurchaseOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppleInAppPurchaseOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quantity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PurchaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PurchaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PurchaseDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PurchaseDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAppleInAppPurchaseOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAppleInAppPurchaseOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAppleInAppPurchaseOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAppleInAppPurchaseOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAppleInAppPurchaseOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAppleInAppPurchaseOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAppleInAppPurchaseOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAppleInAppPurchaseOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAppleInAppPurchaseOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAppleInAppPurchaseOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAppleInAppPurchaseOrder = fmt.Errorf("proto: unexpected end of group")
)
