apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      # volumes:
      # - configMap:
      #     name: {{ .Release.Name }}
      #   name: {{ .Release.Name }}
      hostAliases:
      - ip: "34.105.11.201"
        hostnames:
        - "mongodb-1-servers-vm-0"
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          # volumeMounts:
          # - name: {{ .Release.Name }}
          #   mountPath: /settings.json
          #   readOnly: false
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
{{- include "ports.pod" . | indent 8 }}
          env:
            - name: ROOT_URL
              value: http://wallet.pylons.tech
            - name: MONGO_URL
              value: {{ .Values.mongoURL }}
            - name: PORT
              value: "80"
            - name: METEOR_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: settings.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 10