name: pylons_sdk
description: Pylons sdk connects client apps to the pylons wallet. It helps the client apps to perform actions on the pylons chain via wallet.
version: 0.1.4
homepage: https://www.pylons.tech/
repository: https://github.com/Pylons-tech/pylons

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dartz: ^0.10.0
  decimal: ^2.1.0
  equatable: ^2.0.3
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  protobuf: ^2.0.0
  uni_links: ^0.5.1
  uni_links_platform_interface: ^1.0.0
  url_launcher: ^6.1.2
  
dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito:
  
flutter:
  assets:
    - assets/loading.gif
