// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pylons/pylons/cookbook.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Cookbook struct {
	Creator      string            `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id           string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeVersion  uint64            `protobuf:"varint,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	Name         string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description  string            `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Developer    string            `protobuf:"bytes,6,opt,name=developer,proto3" json:"developer,omitempty"`
	Version      string            `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	SupportEmail string            `protobuf:"bytes,8,opt,name=support_email,json=supportEmail,proto3" json:"support_email,omitempty"`
	Enabled      bool              `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RecipeLimit  map[string]*Limit `protobuf:"bytes,10,rep,name=recipe_limit,json=recipeLimit,proto3" json:"recipe_limit,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Cookbook) Reset()         { *m = Cookbook{} }
func (m *Cookbook) String() string { return proto.CompactTextString(m) }
func (*Cookbook) ProtoMessage()    {}
func (*Cookbook) Descriptor() ([]byte, []int) {
	return fileDescriptor_3974a4f725435df2, []int{0}
}
func (m *Cookbook) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cookbook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cookbook.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cookbook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookbook.Merge(m, src)
}
func (m *Cookbook) XXX_Size() int {
	return m.Size()
}
func (m *Cookbook) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookbook.DiscardUnknown(m)
}

var xxx_messageInfo_Cookbook proto.InternalMessageInfo

func (m *Cookbook) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Cookbook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cookbook) GetNodeVersion() uint64 {
	if m != nil {
		return m.NodeVersion
	}
	return 0
}

func (m *Cookbook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cookbook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Cookbook) GetDeveloper() string {
	if m != nil {
		return m.Developer
	}
	return ""
}

func (m *Cookbook) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Cookbook) GetSupportEmail() string {
	if m != nil {
		return m.SupportEmail
	}
	return ""
}

func (m *Cookbook) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Cookbook) GetRecipeLimit() map[string]*Limit {
	if m != nil {
		return m.RecipeLimit
	}
	return nil
}

type Limit struct {
	Quantity     uint64 `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty,string"`
	AmountMinted uint64 `protobuf:"varint,2,opt,name=amount_minted,json=amountMinted,proto3" json:"amount_minted,omitempty,string"`
}

func (m *Limit) Reset()         { *m = Limit{} }
func (m *Limit) String() string { return proto.CompactTextString(m) }
func (*Limit) ProtoMessage()    {}
func (*Limit) Descriptor() ([]byte, []int) {
	return fileDescriptor_3974a4f725435df2, []int{1}
}
func (m *Limit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Limit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Limit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Limit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limit.Merge(m, src)
}
func (m *Limit) XXX_Size() int {
	return m.Size()
}
func (m *Limit) XXX_DiscardUnknown() {
	xxx_messageInfo_Limit.DiscardUnknown(m)
}

var xxx_messageInfo_Limit proto.InternalMessageInfo

func (m *Limit) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Limit) GetAmountMinted() uint64 {
	if m != nil {
		return m.AmountMinted
	}
	return 0
}

func init() {
	proto.RegisterType((*Cookbook)(nil), "pylons.pylons.Cookbook")
	proto.RegisterMapType((map[string]*Limit)(nil), "pylons.pylons.Cookbook.RecipeLimitEntry")
	proto.RegisterType((*Limit)(nil), "pylons.pylons.limit")
}

func init() { proto.RegisterFile("pylons/pylons/cookbook.proto", fileDescriptor_3974a4f725435df2) }

var fileDescriptor_3974a4f725435df2 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xe3, 0xc4, 0x69, 0x93, 0x75, 0xf2, 0x53, 0xb5, 0xea, 0xc1, 0xbf, 0xa8, 0xb8, 0x26,
	0x5c, 0x2c, 0x14, 0x6c, 0xb5, 0x5c, 0x80, 0x63, 0x50, 0xe1, 0x00, 0x48, 0xc8, 0x42, 0x1c, 0xb8,
	0x44, 0xfe, 0x33, 0x4a, 0x57, 0xb1, 0x77, 0xcc, 0x7a, 0x1d, 0xe1, 0x67, 0xe0, 0xc2, 0x5b, 0xf0,
	0x2a, 0x1c, 0x7b, 0xe4, 0x54, 0xa1, 0xe4, 0xd6, 0xa7, 0x40, 0xde, 0xb5, 0x29, 0x2d, 0xa7, 0x9d,
	0xf9, 0x7c, 0xbf, 0x33, 0x3b, 0x1e, 0x2f, 0x39, 0x29, 0xea, 0x0c, 0x79, 0x19, 0xb4, 0x47, 0x82,
	0xb8, 0x89, 0x11, 0x37, 0x7e, 0x21, 0x50, 0x22, 0x9d, 0x6a, 0xec, 0xeb, 0x63, 0x76, 0xbc, 0xc6,
	0x35, 0x2a, 0x25, 0x68, 0x22, 0x6d, 0x9a, 0x39, 0x09, 0x96, 0x39, 0x96, 0x41, 0x1c, 0x95, 0x10,
	0x6c, 0xcf, 0x62, 0x90, 0xd1, 0x59, 0x90, 0x20, 0xe3, 0x5a, 0x9f, 0x7f, 0x1f, 0x90, 0xd1, 0xcb,
	0xb6, 0x2f, 0xb5, 0xc9, 0x61, 0x22, 0x20, 0x92, 0x28, 0x6c, 0xc3, 0x35, 0xbc, 0x71, 0xd8, 0xa5,
	0xf4, 0x3f, 0xd2, 0x67, 0xa9, 0xdd, 0x57, 0xb0, 0xcf, 0x52, 0xfa, 0x90, 0x4c, 0x38, 0xa6, 0xb0,
	0xda, 0x82, 0x28, 0x19, 0x72, 0x7b, 0xe0, 0x1a, 0x9e, 0x19, 0x5a, 0x0d, 0xfb, 0xa8, 0x11, 0xa5,
	0xc4, 0xe4, 0x51, 0x0e, 0xb6, 0xa9, 0x8a, 0x54, 0x4c, 0x5d, 0x62, 0xa5, 0x50, 0x26, 0x82, 0x15,
	0xb2, 0xa9, 0x1a, 0x2a, 0xe9, 0x6f, 0x44, 0x4f, 0xc8, 0x38, 0x85, 0x2d, 0x64, 0x58, 0x80, 0xb0,
	0x0f, 0x94, 0x7e, 0x0b, 0x9a, 0x01, 0xbb, 0x1b, 0x0f, 0xf5, 0x80, 0x6d, 0x4a, 0x1f, 0x91, 0x69,
	0x59, 0x15, 0x05, 0x0a, 0xb9, 0x82, 0x3c, 0x62, 0x99, 0x3d, 0x52, 0xfa, 0xa4, 0x85, 0x17, 0x0d,
	0x6b, 0xca, 0x81, 0x47, 0x71, 0x06, 0xa9, 0x3d, 0x76, 0x0d, 0x6f, 0x14, 0x76, 0x29, 0x7d, 0x43,
	0x26, 0x02, 0x12, 0x56, 0xc0, 0x2a, 0x63, 0x39, 0x93, 0x36, 0x71, 0x07, 0x9e, 0x75, 0xee, 0xf9,
	0x77, 0x56, 0xec, 0x77, 0x8b, 0xf2, 0x43, 0xe5, 0x7d, 0xdb, 0x58, 0x2f, 0xb8, 0x14, 0x75, 0x68,
	0x89, 0x5b, 0x32, 0xfb, 0x40, 0x8e, 0xee, 0x1b, 0xe8, 0x11, 0x19, 0x6c, 0xa0, 0x6e, 0xd7, 0xda,
	0x84, 0xf4, 0x31, 0x19, 0x6e, 0xa3, 0xac, 0x02, 0xb5, 0x55, 0xeb, 0xfc, 0xf8, 0xde, 0x5d, 0x6a,
	0x8e, 0x50, 0x5b, 0x5e, 0xf4, 0x9f, 0x19, 0xf3, 0xaf, 0x06, 0x19, 0x2a, 0x48, 0x9f, 0x93, 0xd1,
	0xe7, 0x2a, 0xe2, 0x92, 0x49, 0xdd, 0xd0, 0x5c, 0x3e, 0xb8, 0xb9, 0x3e, 0xfd, 0xbf, 0x63, 0x0b,
	0xcc, 0x99, 0x84, 0xbc, 0x90, 0xf5, 0xa2, 0x94, 0x82, 0xf1, 0x75, 0xf8, 0xc7, 0x4e, 0x5f, 0x93,
	0x69, 0x94, 0x63, 0xc5, 0xe5, 0x2a, 0x67, 0x5c, 0x82, 0xfe, 0xa5, 0xe6, 0x72, 0x7e, 0x73, 0x7d,
	0xea, 0xdc, 0x11, 0xfe, 0x6d, 0x32, 0xd1, 0xfa, 0x3b, 0x25, 0x2f, 0x5f, 0xfd, 0xd8, 0x39, 0xc6,
	0xd5, 0xce, 0x31, 0x7e, 0xed, 0x1c, 0xe3, 0xdb, 0xde, 0xe9, 0x5d, 0xed, 0x9d, 0xde, 0xcf, 0xbd,
	0xd3, 0xfb, 0xb4, 0x58, 0x33, 0x79, 0x59, 0xc5, 0x7e, 0x82, 0x79, 0xf0, 0x5e, 0x7d, 0xcb, 0x13,
	0x09, 0xc9, 0x65, 0xf7, 0x88, 0xbf, 0x74, 0x81, 0xac, 0x0b, 0x28, 0xe3, 0x03, 0xf5, 0x0c, 0x9f,
	0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x11, 0x4a, 0x0a, 0xeb, 0x02, 0x00, 0x00,
}

func (m *Cookbook) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cookbook) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cookbook) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecipeLimit) > 0 {
		for k := range m.RecipeLimit {
			v := m.RecipeLimit[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintCookbook(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCookbook(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCookbook(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.SupportEmail) > 0 {
		i -= len(m.SupportEmail)
		copy(dAtA[i:], m.SupportEmail)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.SupportEmail)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Developer) > 0 {
		i -= len(m.Developer)
		copy(dAtA[i:], m.Developer)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Developer)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.NodeVersion != 0 {
		i = encodeVarintCookbook(dAtA, i, uint64(m.NodeVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCookbook(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Limit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Limit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Limit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AmountMinted != 0 {
		i = encodeVarintCookbook(dAtA, i, uint64(m.AmountMinted))
		i--
		dAtA[i] = 0x10
	}
	if m.Quantity != 0 {
		i = encodeVarintCookbook(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCookbook(dAtA []byte, offset int, v uint64) int {
	offset -= sovCookbook(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Cookbook) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	if m.NodeVersion != 0 {
		n += 1 + sovCookbook(uint64(m.NodeVersion))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	l = len(m.Developer)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	l = len(m.SupportEmail)
	if l > 0 {
		n += 1 + l + sovCookbook(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	if len(m.RecipeLimit) > 0 {
		for k, v := range m.RecipeLimit {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovCookbook(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovCookbook(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovCookbook(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Limit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Quantity != 0 {
		n += 1 + sovCookbook(uint64(m.Quantity))
	}
	if m.AmountMinted != 0 {
		n += 1 + sovCookbook(uint64(m.AmountMinted))
	}
	return n
}

func sovCookbook(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCookbook(x uint64) (n int) {
	return sovCookbook(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Cookbook) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCookbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cookbook: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cookbook: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeVersion", wireType)
			}
			m.NodeVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Developer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Developer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCookbook
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCookbook
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RecipeLimit == nil {
				m.RecipeLimit = make(map[string]*Limit)
			}
			var mapkey string
			var mapvalue *Limit
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCookbook
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCookbook
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCookbook
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCookbook
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCookbook
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthCookbook
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthCookbook
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Limit{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCookbook(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCookbook
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.RecipeLimit[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCookbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCookbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Limit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCookbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: limit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: limit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMinted", wireType)
			}
			m.AmountMinted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMinted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCookbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCookbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCookbook(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCookbook
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCookbook
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCookbook
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCookbook
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCookbook
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCookbook        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCookbook          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCookbook = fmt.Errorf("proto: unexpected end of group")
)
