// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pylons/google_iap_order.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GoogleInAppPurchaseOrder struct {
	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProductId         string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseToken     string `protobuf:"bytes,3,opt,name=purchase_token,json=purchaseToken,proto3" json:"purchase_token,omitempty"`
	ReceiptDataBase64 string `protobuf:"bytes,4,opt,name=receipt_data_base64,json=receiptDataBase64,proto3" json:"receipt_data_base64,omitempty"`
	Signature         string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *GoogleInAppPurchaseOrder) Reset()         { *m = GoogleInAppPurchaseOrder{} }
func (m *GoogleInAppPurchaseOrder) String() string { return proto.CompactTextString(m) }
func (*GoogleInAppPurchaseOrder) ProtoMessage()    {}
func (*GoogleInAppPurchaseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a9266864181088e, []int{0}
}
func (m *GoogleInAppPurchaseOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GoogleInAppPurchaseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GoogleInAppPurchaseOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GoogleInAppPurchaseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleInAppPurchaseOrder.Merge(m, src)
}
func (m *GoogleInAppPurchaseOrder) XXX_Size() int {
	return m.Size()
}
func (m *GoogleInAppPurchaseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleInAppPurchaseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleInAppPurchaseOrder proto.InternalMessageInfo

func (m *GoogleInAppPurchaseOrder) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *GoogleInAppPurchaseOrder) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *GoogleInAppPurchaseOrder) GetPurchaseToken() string {
	if m != nil {
		return m.PurchaseToken
	}
	return ""
}

func (m *GoogleInAppPurchaseOrder) GetReceiptDataBase64() string {
	if m != nil {
		return m.ReceiptDataBase64
	}
	return ""
}

func (m *GoogleInAppPurchaseOrder) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*GoogleInAppPurchaseOrder)(nil), "Pylonstech.pylons.pylons.GoogleInAppPurchaseOrder")
}

func init() { proto.RegisterFile("pylons/google_iap_order.proto", fileDescriptor_1a9266864181088e) }

var fileDescriptor_1a9266864181088e = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x3f, 0x4b, 0xc4, 0x30,
	0x18, 0xc6, 0x1b, 0xff, 0xd2, 0x80, 0x82, 0x71, 0xc9, 0xe0, 0x05, 0x11, 0x04, 0x07, 0x6d, 0x07,
	0xc5, 0xdd, 0x43, 0x94, 0x9b, 0x3c, 0xc4, 0xc9, 0x25, 0xa4, 0xe9, 0x4b, 0x5b, 0x3c, 0x9b, 0x90,
	0xbe, 0x05, 0xef, 0x5b, 0xf8, 0xb1, 0x6e, 0xbc, 0xd1, 0x51, 0xda, 0x2f, 0x22, 0x4d, 0x53, 0xa7,
	0x24, 0xcf, 0xef, 0x79, 0xf3, 0xc2, 0x8f, 0xce, 0xec, 0x7a, 0x65, 0xea, 0x26, 0x2d, 0x8c, 0x29,
	0x56, 0x20, 0x2b, 0x65, 0xa5, 0x71, 0x39, 0xb8, 0xc4, 0x3a, 0x83, 0x86, 0xf1, 0xa5, 0xc7, 0x08,
	0xba, 0x4c, 0xc6, 0x66, 0x38, 0x2e, 0x36, 0x84, 0xf2, 0x67, 0x3f, 0xb4, 0xa8, 0x1f, 0xac, 0x5d,
	0xb6, 0x4e, 0x97, 0xaa, 0x81, 0x97, 0x61, 0x98, 0x71, 0x7a, 0xa8, 0x1d, 0x28, 0x34, 0x8e, 0x93,
	0x73, 0x72, 0x15, 0xbf, 0x4e, 0x4f, 0x36, 0xa3, 0xd4, 0x3a, 0x93, 0xb7, 0x1a, 0x65, 0x95, 0xf3,
	0x1d, 0x0f, 0xe3, 0x90, 0x2c, 0x72, 0x76, 0x49, 0x8f, 0x6d, 0xf8, 0x49, 0xa2, 0xf9, 0x80, 0x9a,
	0xef, 0xfa, 0xca, 0xd1, 0x94, 0xbe, 0x0d, 0x21, 0x4b, 0xe8, 0xa9, 0x03, 0x0d, 0x95, 0x45, 0x99,
	0x2b, 0x54, 0x32, 0x53, 0x0d, 0xdc, 0xdf, 0xf1, 0x3d, 0xdf, 0x3d, 0x09, 0xe8, 0x51, 0xa1, 0x9a,
	0x7b, 0xc0, 0xce, 0x68, 0xdc, 0x54, 0x45, 0xad, 0xb0, 0x75, 0xc0, 0xf7, 0xc7, 0xa5, 0xff, 0xc1,
	0xfc, 0x69, 0xd3, 0x09, 0xb2, 0xed, 0x04, 0xf9, 0xed, 0x04, 0xf9, 0xee, 0x45, 0xb4, 0xed, 0x45,
	0xf4, 0xd3, 0x8b, 0xe8, 0xfd, 0xba, 0xa8, 0xb0, 0x6c, 0xb3, 0x44, 0x9b, 0xcf, 0x74, 0x34, 0x71,
	0x33, 0xa8, 0x48, 0x83, 0xb4, 0xaf, 0xe9, 0x82, 0x6b, 0x0b, 0x4d, 0x76, 0xe0, 0x9d, 0xdd, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x31, 0x6b, 0x10, 0x54, 0x01, 0x00, 0x00,
}

func (m *GoogleInAppPurchaseOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GoogleInAppPurchaseOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GoogleInAppPurchaseOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintGoogleIapOrder(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceiptDataBase64) > 0 {
		i -= len(m.ReceiptDataBase64)
		copy(dAtA[i:], m.ReceiptDataBase64)
		i = encodeVarintGoogleIapOrder(dAtA, i, uint64(len(m.ReceiptDataBase64)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PurchaseToken) > 0 {
		i -= len(m.PurchaseToken)
		copy(dAtA[i:], m.PurchaseToken)
		i = encodeVarintGoogleIapOrder(dAtA, i, uint64(len(m.PurchaseToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProductId) > 0 {
		i -= len(m.ProductId)
		copy(dAtA[i:], m.ProductId)
		i = encodeVarintGoogleIapOrder(dAtA, i, uint64(len(m.ProductId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGoogleIapOrder(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGoogleIapOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovGoogleIapOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GoogleInAppPurchaseOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGoogleIapOrder(uint64(l))
	}
	l = len(m.ProductId)
	if l > 0 {
		n += 1 + l + sovGoogleIapOrder(uint64(l))
	}
	l = len(m.PurchaseToken)
	if l > 0 {
		n += 1 + l + sovGoogleIapOrder(uint64(l))
	}
	l = len(m.ReceiptDataBase64)
	if l > 0 {
		n += 1 + l + sovGoogleIapOrder(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovGoogleIapOrder(uint64(l))
	}
	return n
}

func sovGoogleIapOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGoogleIapOrder(x uint64) (n int) {
	return sovGoogleIapOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GoogleInAppPurchaseOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGoogleIapOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoogleInAppPurchaseOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoogleInAppPurchaseOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PurchaseToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PurchaseToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptDataBase64", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptDataBase64 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGoogleIapOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGoogleIapOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGoogleIapOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGoogleIapOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGoogleIapOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGoogleIapOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGoogleIapOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGoogleIapOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGoogleIapOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGoogleIapOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGoogleIapOrder = fmt.Errorf("proto: unexpected end of group")
)
