// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pylons/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetRecipeRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetRecipeRequest) Reset()         { *m = QueryGetRecipeRequest{} }
func (m *QueryGetRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecipeRequest) ProtoMessage()    {}
func (*QueryGetRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{0}
}
func (m *QueryGetRecipeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecipeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecipeRequest.Merge(m, src)
}
func (m *QueryGetRecipeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecipeRequest proto.InternalMessageInfo

func (m *QueryGetRecipeRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetRecipeResponse struct {
	Recipe *Recipe `protobuf:"bytes,1,opt,name=Recipe,proto3" json:"Recipe,omitempty"`
}

func (m *QueryGetRecipeResponse) Reset()         { *m = QueryGetRecipeResponse{} }
func (m *QueryGetRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecipeResponse) ProtoMessage()    {}
func (*QueryGetRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{1}
}
func (m *QueryGetRecipeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecipeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecipeResponse.Merge(m, src)
}
func (m *QueryGetRecipeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecipeResponse proto.InternalMessageInfo

func (m *QueryGetRecipeResponse) GetRecipe() *Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

type QueryListCookbookByCreatorRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryListCookbookByCreatorRequest) Reset()         { *m = QueryListCookbookByCreatorRequest{} }
func (m *QueryListCookbookByCreatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListCookbookByCreatorRequest) ProtoMessage()    {}
func (*QueryListCookbookByCreatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{2}
}
func (m *QueryListCookbookByCreatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListCookbookByCreatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListCookbookByCreatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListCookbookByCreatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListCookbookByCreatorRequest.Merge(m, src)
}
func (m *QueryListCookbookByCreatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListCookbookByCreatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListCookbookByCreatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListCookbookByCreatorRequest proto.InternalMessageInfo

func (m *QueryListCookbookByCreatorRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryListCookbookByCreatorResponse struct {
	Cookbooks []Cookbook `protobuf:"bytes,1,rep,name=Cookbooks,proto3" json:"Cookbooks"`
}

func (m *QueryListCookbookByCreatorResponse) Reset()         { *m = QueryListCookbookByCreatorResponse{} }
func (m *QueryListCookbookByCreatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListCookbookByCreatorResponse) ProtoMessage()    {}
func (*QueryListCookbookByCreatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{3}
}
func (m *QueryListCookbookByCreatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListCookbookByCreatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListCookbookByCreatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListCookbookByCreatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListCookbookByCreatorResponse.Merge(m, src)
}
func (m *QueryListCookbookByCreatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListCookbookByCreatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListCookbookByCreatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListCookbookByCreatorResponse proto.InternalMessageInfo

func (m *QueryListCookbookByCreatorResponse) GetCookbooks() []Cookbook {
	if m != nil {
		return m.Cookbooks
	}
	return nil
}

type QueryGetCookbookRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCookbookRequest) Reset()         { *m = QueryGetCookbookRequest{} }
func (m *QueryGetCookbookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCookbookRequest) ProtoMessage()    {}
func (*QueryGetCookbookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{4}
}
func (m *QueryGetCookbookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCookbookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCookbookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCookbookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCookbookRequest.Merge(m, src)
}
func (m *QueryGetCookbookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCookbookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCookbookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCookbookRequest proto.InternalMessageInfo

func (m *QueryGetCookbookRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCookbookResponse struct {
	Cookbook *Cookbook `protobuf:"bytes,1,opt,name=Cookbook,proto3" json:"Cookbook,omitempty"`
}

func (m *QueryGetCookbookResponse) Reset()         { *m = QueryGetCookbookResponse{} }
func (m *QueryGetCookbookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCookbookResponse) ProtoMessage()    {}
func (*QueryGetCookbookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbe4a0dc0744f938, []int{5}
}
func (m *QueryGetCookbookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCookbookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCookbookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCookbookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCookbookResponse.Merge(m, src)
}
func (m *QueryGetCookbookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCookbookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCookbookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCookbookResponse proto.InternalMessageInfo

func (m *QueryGetCookbookResponse) GetCookbook() *Cookbook {
	if m != nil {
		return m.Cookbook
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetRecipeRequest)(nil), "Pylonstech.pylons.pylons.QueryGetRecipeRequest")
	proto.RegisterType((*QueryGetRecipeResponse)(nil), "Pylonstech.pylons.pylons.QueryGetRecipeResponse")
	proto.RegisterType((*QueryListCookbookByCreatorRequest)(nil), "Pylonstech.pylons.pylons.QueryListCookbookByCreatorRequest")
	proto.RegisterType((*QueryListCookbookByCreatorResponse)(nil), "Pylonstech.pylons.pylons.QueryListCookbookByCreatorResponse")
	proto.RegisterType((*QueryGetCookbookRequest)(nil), "Pylonstech.pylons.pylons.QueryGetCookbookRequest")
	proto.RegisterType((*QueryGetCookbookResponse)(nil), "Pylonstech.pylons.pylons.QueryGetCookbookResponse")
}

func init() { proto.RegisterFile("pylons/query.proto", fileDescriptor_dbe4a0dc0744f938) }

var fileDescriptor_dbe4a0dc0744f938 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xbf, 0x6f, 0xd4, 0x30,
	0x14, 0xc7, 0xcf, 0x94, 0x16, 0xea, 0x6e, 0xa6, 0x57, 0xa2, 0x08, 0xa5, 0x57, 0x2f, 0x54, 0x88,
	0xc6, 0xdc, 0xb1, 0x20, 0xf1, 0x63, 0x68, 0xa5, 0xb2, 0x30, 0x40, 0xc6, 0x6e, 0x49, 0xb0, 0xd2,
	0xa8, 0x69, 0x5e, 0x1a, 0xfb, 0x50, 0xa3, 0xaa, 0x0b, 0x2b, 0x0b, 0x52, 0xff, 0x1c, 0xfe, 0x81,
	0x8e, 0x95, 0x58, 0x98, 0x10, 0xba, 0x63, 0xe1, 0xbf, 0x40, 0xb1, 0x9f, 0x5b, 0x38, 0x7a, 0xd7,
	0xd2, 0x29, 0xce, 0xd7, 0xef, 0xfb, 0xde, 0xc7, 0xcf, 0xcf, 0x94, 0x55, 0x4d, 0x01, 0xa5, 0x12,
	0x07, 0x43, 0x59, 0x37, 0x61, 0x55, 0x83, 0x06, 0xe6, 0xbd, 0x35, 0x9a, 0x96, 0xe9, 0x6e, 0x68,
	0xb7, 0xf1, 0xe3, 0x3f, 0xc8, 0x00, 0xb2, 0x42, 0x8a, 0xb8, 0xca, 0x45, 0x5c, 0x96, 0xa0, 0x63,
	0x9d, 0x9b, 0xed, 0xd6, 0xe7, 0x3f, 0x4a, 0x41, 0xed, 0x83, 0x12, 0x49, 0xac, 0xa4, 0x4d, 0x28,
	0x3e, 0xf4, 0x13, 0xa9, 0xe3, 0xbe, 0xa8, 0xe2, 0x2c, 0x2f, 0x4d, 0x30, 0xc6, 0x2e, 0x67, 0x90,
	0x81, 0x59, 0x8a, 0x76, 0x85, 0xea, 0x3d, 0xa4, 0xa9, 0x65, 0x9a, 0x57, 0x12, 0xc5, 0x2e, 0x8a,
	0x29, 0xc0, 0x5e, 0x02, 0xb0, 0x67, 0x65, 0xbe, 0x41, 0xbb, 0xef, 0xda, 0x1a, 0xaf, 0xa5, 0x8e,
	0x4c, 0x78, 0x24, 0x0f, 0x86, 0x52, 0x69, 0xb6, 0x4c, 0xe7, 0xf3, 0xf2, 0xbd, 0x3c, 0xf4, 0x48,
	0x8f, 0xac, 0x2f, 0x46, 0xf6, 0x87, 0x47, 0x74, 0x65, 0x32, 0x5c, 0x55, 0x50, 0x2a, 0xc9, 0x9e,
	0xd1, 0x05, 0xab, 0x18, 0xc3, 0xd2, 0xa0, 0x17, 0x4e, 0x3b, 0x7f, 0x88, 0x4e, 0x8c, 0xe7, 0x2f,
	0xe9, 0x9a, 0xc9, 0xf9, 0x26, 0x57, 0x7a, 0x0b, 0xe9, 0x36, 0x9b, 0xad, 0x5a, 0xc6, 0x1a, 0x6a,
	0x87, 0xe3, 0xd1, 0x3b, 0xa9, 0x55, 0x10, 0xc8, 0xfd, 0xf2, 0x82, 0xf2, 0x59, 0x76, 0xc4, 0xdb,
	0xa6, 0x8b, 0x6e, 0x53, 0x79, 0xa4, 0x37, 0xb7, 0xbe, 0x34, 0xe0, 0xd3, 0x09, 0xcf, 0xf3, 0xdc,
	0x3e, 0xfd, 0xbe, 0xda, 0x89, 0x2e, 0xac, 0x5c, 0xd0, 0xfb, 0xae, 0x01, 0x4e, 0x9c, 0xdd, 0xb1,
	0x1d, 0xea, 0xfd, 0x6b, 0x40, 0xa8, 0x57, 0xf4, 0xae, 0xd3, 0xb0, 0x6b, 0xd7, 0x60, 0x8a, 0xce,
	0x3d, 0x83, 0x5f, 0x73, 0x74, 0xde, 0x24, 0x67, 0x9f, 0x88, 0x6b, 0x3f, 0x13, 0xd3, 0x53, 0x5c,
	0x7a, 0xd3, 0xfe, 0x93, 0xeb, 0x1b, 0x2c, 0x37, 0x0f, 0x3e, 0x7e, 0xfd, 0x79, 0x72, 0xcb, 0x63,
	0x2b, 0xe2, 0xaf, 0x49, 0x13, 0x47, 0xe6, 0xc8, 0xc7, 0xec, 0x0b, 0xa1, 0xdd, 0x4b, 0xaf, 0x83,
	0x3d, 0xbf, 0xa2, 0xd6, 0xac, 0x19, 0xf0, 0x5f, 0xdc, 0xcc, 0x8c, 0xd0, 0x0f, 0x0d, 0xf4, 0x1a,
	0x5b, 0x75, 0xd0, 0xc5, 0x1f, 0xe1, 0x4a, 0x1c, 0xe1, 0x3c, 0x1d, 0xb3, 0x13, 0x72, 0x71, 0x2d,
	0xac, 0x7f, 0x75, 0x73, 0x26, 0xe6, 0xc0, 0x1f, 0xfc, 0x8f, 0x05, 0xe1, 0x7a, 0x06, 0xce, 0x67,
	0x9e, 0x98, 0x78, 0xa6, 0xae, 0xa7, 0x9b, 0xdb, 0xa7, 0xa3, 0x80, 0x9c, 0x8d, 0x02, 0xf2, 0x63,
	0x14, 0x90, 0xcf, 0xe3, 0xa0, 0x73, 0x36, 0x0e, 0x3a, 0xdf, 0xc6, 0x41, 0x67, 0xe7, 0x71, 0x96,
	0xeb, 0xdd, 0x61, 0x12, 0xa6, 0xb0, 0x2f, 0x6c, 0xe5, 0x8d, 0xb6, 0xb4, 0xcb, 0x74, 0xe8, 0x16,
	0xba, 0xa9, 0xa4, 0x4a, 0x16, 0xcc, 0xbb, 0x7f, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x66, 0xc6,
	0xdf, 0x27, 0xb3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a recipe by index.
	Recipe(ctx context.Context, in *QueryGetRecipeRequest, opts ...grpc.CallOption) (*QueryGetRecipeResponse, error)
	// Queries a list of listCookbookByCreator items.
	ListCookbookByCreator(ctx context.Context, in *QueryListCookbookByCreatorRequest, opts ...grpc.CallOption) (*QueryListCookbookByCreatorResponse, error)
	// Queries a cookbook by index.
	Cookbook(ctx context.Context, in *QueryGetCookbookRequest, opts ...grpc.CallOption) (*QueryGetCookbookResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Recipe(ctx context.Context, in *QueryGetRecipeRequest, opts ...grpc.CallOption) (*QueryGetRecipeResponse, error) {
	out := new(QueryGetRecipeResponse)
	err := c.cc.Invoke(ctx, "/Pylonstech.pylons.pylons.Query/Recipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListCookbookByCreator(ctx context.Context, in *QueryListCookbookByCreatorRequest, opts ...grpc.CallOption) (*QueryListCookbookByCreatorResponse, error) {
	out := new(QueryListCookbookByCreatorResponse)
	err := c.cc.Invoke(ctx, "/Pylonstech.pylons.pylons.Query/ListCookbookByCreator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Cookbook(ctx context.Context, in *QueryGetCookbookRequest, opts ...grpc.CallOption) (*QueryGetCookbookResponse, error) {
	out := new(QueryGetCookbookResponse)
	err := c.cc.Invoke(ctx, "/Pylonstech.pylons.pylons.Query/Cookbook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a recipe by index.
	Recipe(context.Context, *QueryGetRecipeRequest) (*QueryGetRecipeResponse, error)
	// Queries a list of listCookbookByCreator items.
	ListCookbookByCreator(context.Context, *QueryListCookbookByCreatorRequest) (*QueryListCookbookByCreatorResponse, error)
	// Queries a cookbook by index.
	Cookbook(context.Context, *QueryGetCookbookRequest) (*QueryGetCookbookResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Recipe(ctx context.Context, req *QueryGetRecipeRequest) (*QueryGetRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recipe not implemented")
}
func (*UnimplementedQueryServer) ListCookbookByCreator(ctx context.Context, req *QueryListCookbookByCreatorRequest) (*QueryListCookbookByCreatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCookbookByCreator not implemented")
}
func (*UnimplementedQueryServer) Cookbook(ctx context.Context, req *QueryGetCookbookRequest) (*QueryGetCookbookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cookbook not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Recipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Recipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pylonstech.pylons.pylons.Query/Recipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Recipe(ctx, req.(*QueryGetRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListCookbookByCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListCookbookByCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListCookbookByCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pylonstech.pylons.pylons.Query/ListCookbookByCreator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListCookbookByCreator(ctx, req.(*QueryListCookbookByCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Cookbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCookbookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Cookbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pylonstech.pylons.pylons.Query/Cookbook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Cookbook(ctx, req.(*QueryGetCookbookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pylonstech.pylons.pylons.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recipe",
			Handler:    _Query_Recipe_Handler,
		},
		{
			MethodName: "ListCookbookByCreator",
			Handler:    _Query_ListCookbookByCreator_Handler,
		},
		{
			MethodName: "Cookbook",
			Handler:    _Query_Cookbook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pylons/query.proto",
}

func (m *QueryGetRecipeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecipeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecipeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecipeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecipeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecipeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Recipe != nil {
		{
			size, err := m.Recipe.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListCookbookByCreatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListCookbookByCreatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListCookbookByCreatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListCookbookByCreatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListCookbookByCreatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListCookbookByCreatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cookbooks) > 0 {
		for iNdEx := len(m.Cookbooks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cookbooks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCookbookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCookbookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCookbookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCookbookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCookbookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCookbookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cookbook != nil {
		{
			size, err := m.Cookbook.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetRecipeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRecipeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Recipe != nil {
		l = m.Recipe.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListCookbookByCreatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListCookbookByCreatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Cookbooks) > 0 {
		for _, e := range m.Cookbooks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetCookbookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCookbookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cookbook != nil {
		l = m.Cookbook.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetRecipeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecipeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecipeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecipeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecipeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecipeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipe", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Recipe == nil {
				m.Recipe = &Recipe{}
			}
			if err := m.Recipe.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListCookbookByCreatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListCookbookByCreatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListCookbookByCreatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListCookbookByCreatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListCookbookByCreatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListCookbookByCreatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cookbooks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cookbooks = append(m.Cookbooks, Cookbook{})
			if err := m.Cookbooks[len(m.Cookbooks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCookbookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCookbookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCookbookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCookbookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCookbookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCookbookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cookbook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cookbook == nil {
				m.Cookbook = &Cookbook{}
			}
			if err := m.Cookbook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
