package types

import (
	"errors"
	"fmt"
	"math/rand"
)

// WeightedOutputs is to make structs which is using weight to be based on
type WeightedOutputs struct {
	ResultEntries []int
	Weight        string
}

func (ol WeightedOutputs) String() string {
	return fmt.Sprintf("WeightedOutputs{ResultEntries: %v, Weight: %v}", ol.ResultEntries, ol.Weight)
}

// GetWeight calculate weight value using program
func (ol WeightedOutputs) GetWeight(ec CelEnvCollection) (int, error) {
	refVal, refErr := ec.Eval(ol.Weight)
	if refErr != nil {
		return 0, refErr
	}

	val64, ok := refVal.Value().(int64)
	if !ok {
		return 0, errors.New("error converting weight value to int64")
	}
	if val64 < 0 {
		return 0, nil
	}
	return int(val64), nil
}

// WeightedOutputsList is a struct to keep items which can be generated by weight;
// ItemOutput and CoinOutput is possible in current stage
type WeightedOutputsList []WeightedOutputs

func (wol WeightedOutputsList) String() string {
	itm := "WeightedOutputsList{"

	for _, output := range wol {
		itm += output.String() + ",\n"
	}

	itm += "}"
	return itm
}

// Actualize generate result entries from WeightedOutputsList
func (wol WeightedOutputsList) Actualize(ec CelEnvCollection) ([]int, error) {
	lastWeight := 0
	var weights []int
	for _, wp := range wol {
		w, err := wp.GetWeight(ec)
		if err != nil {
			return nil, err
		}
		lastWeight += w
		weights = append(weights, lastWeight)
	}
	if len(wol) == 0 {
		return nil, nil
	}

	if lastWeight == 0 {
		return nil, errors.New("total weight of weighted param list shouldn't be zero")
	}
	randWeight := rand.Intn(lastWeight)

	first := 0
	chosenIndex := -1
	for i, weight := range weights {
		if randWeight >= first && randWeight <= weight {
			chosenIndex = i
			break
		}
		first = weight
	}
	return wol[chosenIndex].ResultEntries, nil
}
